# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sparkplug 
email: ray@sparkpl.ug
description: >- # this means to ignore newlines until "baseurl:"
  Building better products for our clients since 2013.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sparkpl.ug" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sparkplugea
github_username:  sparkplugea

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# SEO/Meta settings
author: Sparkplug
twitter:
  username: sparkplugea
social:
  name: Sparkplug
  links:
    - https://twitter.com/sparkplugea
    - https://www.facebook.com/sparkplugea
    - http://www.linkedin.com/company/3104389
    - https://www.github.com/sparkplug
seo:
  name: Sparkplug
  type: Organization

defaults:
  - scope:
      path: ""
    values:
      image: /img/sparkplug-tech-work.jpg

analytics:
  provider               : google # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : UA-40448209-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
